### ISSUE TITLE
nvpy Not Starting

### ISSUE THREAD

**Issue by cnodell** [cpbotha/nvpy#111]
I have installed and run nvpy via debians packet manager and by cloning the git repo and running it from there.

I am using python 2.7.8 on Debian Testing

In both cases there is a flicker as the gui seems to start loading, then it dissapears and I get the error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/CharlesNodell/projects/nvpy/nvpy/__main__.py", line 2, in <module>
    nvpy.main()
  File "nvpy/nvpy.py", line 624, in main
    controller = Controller()
  File "nvpy/nvpy.py", line 227, in __init__
    self.view = view.View(self.config, self.notes_list_model)
  File "nvpy/view.py", line 516, in __init__
    self._create_ui()
  File "nvpy/view.py", line 822, in _create_ui
    search_entry.make_style()
  File "nvpy/search_entry.py", line 59, in make_style
    s1 = Tkinter.PhotoImage("search1", data=data, format="gif -index 0")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3362, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3314, in __init__
    v = self.tk._createbytearray(v)
AttributeError: _createbytearray
```

I am trying to not use simple note syncing, to store notes as text files in a directory. Here are the contents of my ~/.nvpy.cfg:

```
[nvpy]
simplenote_sync = 0
notes_as_txt = 1
txt_path = /home/user/Documents/notes
```

**Comment by cpbotha** [comment]
Damnit! It looks like this is a bug in the debian packaging: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762747

I've just run into it on this updated Ubuntu 14.04 system.

**Comment by cpbotha** [comment]
On another updated Ubuntu 14.04 system, with the same versions of python and python-tk, I can't reproduce this issue. IOW nvpy works like a charm.

The only other difference is that system 1 has python 3.5 installed from a PPA.

**Comment by yuuki0xff** [comment]
This issue is too old.  Latest stable version is fixed many bugs.  Please use the latest version.

If this problem still persists, reopen it again.
