### ISSUE TITLE
Installation fails on Arch

### ISSUE THREAD

**Issue by taohansen** [cpbotha/nvpy#134]
Collecting nvpy
  Downloading nvpy-0.9.7.tar.gz (203kB)
    100% |████████████████████████████████| 204kB 1.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gv27m_3t/nvpy/setup.py", line 3, in <module>
        from nvpy import nvpy
      File "/tmp/pip-build-gv27m_3t/nvpy/nvpy/nvpy.py", line 263
        except ReadError, e:
                        ^
    SyntaxError: invalid syntax

**Comment by taohansen** [comment]
Arch Linux's command for 'pip' defaults to use the latest python. I fixed this by installing pip for python 2.7 then installing the Tkinter package then explicity calling pip2.7 to do the install. For newbies (like me), the documentation on how to install nvPY needs to be MUCH clearer.

Fixed with
* curl -O https://bootstrap.pypa.io/get-pip.py
* python2.7 get-pip.py
* sudo pacman -S tk
* sudo pip2.7 install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
