### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by colibris79** [cpbotha/nvpy#137]
Hi, 
I just did a pip installation, created my nvpy.cfg file with my email and password and I get this error:

```
mik@mik-Lenovo ~ $ nvpy
Traceback (most recent call last):
  File "/usr/local/bin/nvpy", line 9, in <module>
    load_entry_point('nvpy==0.9.7', 'gui_scripts', 'nvpy')()
  File "/usr/local/lib/python2.7/dist-packages/nvpy/nvpy.py", line 732, in main
    config = Config(appdir_full_path)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/nvpy.py", line 126, in __init__
    self.files_read = cp.read(cfg_files)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/mik/.nvpy.cfg, line: 1
'sn_username = myemail@gmail.com\n'
```

Anyhow to solve this?

**Comment by xulfir** [comment]
Add "[nvpy]" to the top of your config file.

**Comment by colibris79** [comment]
Working now! thanks!
