### ISSUE TITLE
setup.py egg info error

### ISSUE THREAD

**Issue by jaapsoft** [cpbotha/nvpy#143]
NVPY install (pip) gives this error. Fedora 25. Python 2.7.13. 

collecting nvpy
  Using cached nvpy-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7Ai3NW/nvpy/setup.py", line 3, in <module>
        from nvpy import nvpy
      File "nvpy/nvpy.py", line 44, in <module>
        import view
      File "nvpy/view.py", line 8, in <module>
        import search_entry
      File "nvpy/search_entry.py", line 11, in <module>
        import tkinter as Tkinter
    ImportError: No module named tkinter
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7Ai3NW/nvpy/

cannot find a solution.

**Comment by brightghost** [comment]
A dozen relevant search results will come up by pasting your ImportError into a search engine.

The code in question first attempts to import `TKinter`, the Python2 name for this module, and failing that then tries to import the Python3 version, `tkinter`. This is where you're getting the ImportError, which suggests your system has neither `TKinter` nor `tkinter`. You may have a partial Python install which does not include TKinter. Although this is part of the Python Standard Library, some systems omit certain more obscure modules on their standard Python install to save space; I'm not familiar with Fedora to tell if this is the case here. You may need to install it from a separate package. Also, if you're trying to build with Python3, note the Readme clarifies that Python3 is not yet supported.

**Comment by Softskills** [comment]
Brightghost, thanks. The amount of found solutions was overwhelming, but no solution was right for me.
Had to add some parts of Python and import a lot of dependencies. Now it works. If I can go back on  that road I will write my solution down .
