### ISSUE TITLE
ImportError: No module named simplenote

### ISSUE THREAD

**Issue by george-somerville-ma** [cpbotha/nvpy#160]
When I try to install via pip, and also when I try to run from a git clone, I get the following error:

ImportError: No module named simplenote

Here's what my terminal says when I try to install from pip:

```
$ pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
Downloading/unpacking nvpy from git+https://github.com/cpbotha/nvpy.git
  Cloning https://github.com/cpbotha/nvpy.git to /tmp/pip-build-WiCiC4/nvpy
  Running setup.py (path:/tmp/pip-build-WiCiC4/nvpy/setup.py) egg_info for package nvpy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-WiCiC4/nvpy/setup.py", line 3, in <module>
        from nvpy import nvpy
      File "nvpy/nvpy.py", line 37, in <module>
        from notes_db import NotesDB, SyncError, ReadError, WriteError
      File "nvpy/notes_db.py", line 15, in <module>
        import simplenote
    ImportError: No module named simplenote
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-WiCiC4/nvpy/setup.py", line 3, in <module>

    from nvpy import nvpy

  File "nvpy/nvpy.py", line 37, in <module>

    from notes_db import NotesDB, SyncError, ReadError, WriteError

  File "nvpy/notes_db.py", line 15, in <module>

    import simplenote

ImportError: No module named simplenote

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-WiCiC4/nvpy                                                                                   
Storing debug log for failure in /home/***/.pip/pip.log
```

And here's what it says when I launch from the git clone:

```
$ ./nvpy.py 
Traceback (most recent call last):
  File "./nvpy.py", line 37, in <module>
    from notes_db import NotesDB, SyncError, ReadError, WriteError
  File "/home/***/nvpy-git/nvpy/nvpy/notes_db.py", line 15, in <module>
    import simplenote
ImportError: No module named simplenote
```

**Comment by yuuki0xff** [comment]
Thanks your bug report.
