### ISSUE TITLE
install SyntaxError

### ISSUE THREAD

**Issue by raingart** [cpbotha/nvpy#161]
```
> sudo pip install nvpy                                                                                                                   3.306s
Collecting nvpy
  Using cached https://files.pythonhosted.org/packages/46/97/b03817c62c47b17914eba7718e9112d6b32ea54982b9b5585dc4cb38f809/nvpy-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pgqnsl98/nvpy/setup.py", line 3, in <module>
        from nvpy import nvpy
      File "/tmp/pip-install-pgqnsl98/nvpy/nvpy/nvpy.py", line 263
        except ReadError, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pgqnsl98/nvpy/
```
or
```
> sudo easy_install nvpy                                                                                                                                [1]
Searching for nvpy
Reading https://pypi.org/simple/nvpy/
Downloading https://files.pythonhosted.org/packages/46/97/b03817c62c47b17914eba7718e9112d6b32ea54982b9b5585dc4cb38f809/nvpy-1.0.0.tar.gz#sha256=f3bf255e03e0032bc21ec871eda9ff16a1d5972bc82c36d2d8bbd13285a6877e
Best match: nvpy 1.0.0
Processing nvpy-1.0.0.tar.gz
Writing /tmp/easy_install-jh3ttlb2/nvpy-1.0.0/setup.cfg
Running nvpy-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jh3ttlb2/nvpy-1.0.0/egg-dist-tmp-fdaycs3_
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-jh3ttlb2/nvpy-1.0.0/setup.py", line 3, in <module>
  File "/tmp/easy_install-jh3ttlb2/nvpy-1.0.0/nvpy/nvpy.py", line 263
    except ReadError, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by yuuki0xff** [comment]
nvpy does not support Python3.  Please run the following command to install nvpy.

```
$ sudo python2 -m pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy' 
```
