### ISSUE TITLE
ImportError: No module named simplenote

### ISSUE THREAD

**Issue by dr-diem** [cpbotha/nvpy#169]
Hi,

I'm having the same issue reported a couple of months back as george-somerville-ma under [Issue #160](https://github.com/cpbotha/nvpy/issues/160) :+1: 

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yan/code/nvpy/nvpy/__main__.py", line 1, in <module>
    import nvpy
  File "nvpy/nvpy.py", line 37, in <module>
    from notes_db import NotesDB, SyncError, ReadError, WriteError
  File "nvpy/notes_db.py", line 17, in <module>
    import simplenote
ImportError: No module named simplenote

What supplies the module named simplenote? Is it supplied in this git and i have some kind of path error going on?

Thanks,

Ian

**Comment by yuuki0xff** [comment]
The module named "simplenote" is external python module.  Please install it on your computer.
https://github.com/mrtazz/simplenote.py

**Comment by dr-diem** [comment]
Excellent, thanks!
