### ISSUE TITLE
AttributeError: 'module' object has no attribute 'simplenote'

### ISSUE THREAD

**Issue by jarmo** [cpbotha/nvpy#173]
I am a long-term nvpy user and did git pull just now to update this software. Running it now results in an error I did not have before:

```
c:\nvpy>python nvpy
Traceback (most recent call last):
  File "C:\tools\python2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\tools\python2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\nvpy\nvpy\__main__.py", line 1, in <module>
    import nvpy
  File "nvpy\nvpy.py", line 37, in <module>
    from notes_db import NotesDB, SyncError, ReadError, WriteError
  File "nvpy\notes_db.py", line 22, in <module>
    simplenote.simplenote.API_KEY = ''.join(reversed(base64.b64decode('...')))
AttributeError: 'module' object has no attribute 'simplenote'
```

**Comment by yuuki0xff** [comment]
Please install the [simplenote.py](https://github.com/mrtazz/simplenote.py) library.
```
c:\nvpy> pip install simplenote
```

You can start the nvpy with the following command.
```
c:\nvpy> python -m nvpy
```

The above method is manual installation method. I recommended that you install the nvpy using pip command as written in the README file.
```
pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
```
