### ISSUE TITLE
Fail to start offline KeyError: 'current' 

### ISSUE THREAD

**Issue by dunindunin** [cpbotha/nvpy#176]
If i am connect to internet there isn't any problem, but if I'm not, I can't open nvpy (since update)
here is the log:

2019-03-30 10:23:15,540 - DEBUG - nvpy logging initialized
2019-03-30 10:23:15,543 - DEBUG - config read from ['/home/dunin/.nvpy.cfg']
2019-03-30 10:23:16,934 - DEBUG - Starting full sync.
2019-03-30 10:23:17,472 - DEBUG - Retrieving full note list from server, could take a while.
2019-03-30 10:23:17,979 - ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nvpy/notes_db.py", line 703, in wrapper
    sync_from_server_errors = self.sync_full_unthreaded()
  File "/usr/local/lib/python2.7/dist-packages/nvpy/notes_db.py", line 765, in sync_full_unthreaded
    nl = self.simplenote.get_note_list()
  File "/usr/local/lib/python2.7/dist-packages/simplenote/simplenote.py", line 297, in get_note_list
    self.current = response_notes["current"]
KeyError: 'current'

**Comment by yuuki0xff** [comment]
Thanks for bug report.
This bug is actually a bug in the simplenote library.  I sent a pull request to fix this bug.  See https://github.com/mrtazz/simplenote.py/pull/25

**Comment by yuuki0xff** [comment]
Fixed this problem on the simplenote.py v2.1.2.

**Comment by yuuki0xff** [comment]
In addition to the simplenote client issue, nvpy has an error handling issue.  Nvpy v1.2.1 has been released to fix this bug.

**Comment by dunindunin** [comment]
Thanks!
