### ISSUE TITLE
nvpy v2.0.0 not starting due to syntax error

### ISSUE THREAD

**Issue by BENR0** [cpbotha/nvpy#190]
After fresh install of nvpy I get the following error when trying to start nvpy:

```python
Traceback (most recent call last):

  File "/usr/local/bin/nvpy", line 11, in <module>
    load_entry_point('nvpy==2.0.0', 'gui_scripts', 'nvpy')()

  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()

  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()

  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/local/lib/python3.5/dist-packages/nvpy/nvpy.py", line 79
    text: str
        ^
SyntaxError: invalid syntax
```

**Comment by yuuki0xff** [comment]
nvPY uses the [Syntax for Variable Annotations](https://www.python.org/dev/peps/pep-0526/) introduced from Python 3.6. Please upgrade the Python to 3.6 or later.
