### ISSUE TITLE
simplenote module seems to be removed from the project

### ISSUE THREAD

**Issue by stuzenz** [cpbotha/nvpy#216]
First, I would like to say I love the project and use it all the time. Many thanks for supporting this project and giving us a great tool for holding our one-liners.

The below printout of the terminal pretty much covers it.
I resolved it through just installing the simplenote module globally - but I believe until now the module was included in the install. I am not sure if this is an issue with the archlinux aur package or done upstream in this source project - the pacman philosophy is to limit changes from the upstream project - so I am running with the assumption that it might be fixed at this project.

```bash
➜ nvpy &          
[1] 5447
Traceback (most recent call last):                                                                                                                 
  File "/usr/bin/nvpy", line 33, in <module>
    sys.exit(load_entry_point('nvpy==2.1.0', 'gui_scripts', 'nvpy')())
  File "/usr/bin/nvpy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/nvpy/nvpy.py", line 38, in <module>
    from .notes_db import NotesDB, SyncError, ReadError, WriteError
  File "/usr/lib/python3.9/site-packages/nvpy/notes_db.py", line 19, in <module>
    import simplenote
ModuleNotFoundError: No module named 'simplenote'
[1]  + 5447 exit 1     nvpy

~ 
➜ pip install simplenote
Defaulting to user installation because normal site-packages is not writeable
Collecting simplenote
  Downloading simplenote-2.1.4.tar.gz (8.2 kB)
Using legacy 'setup.py install' for simplenote, since package 'wheel' is not installed.
Installing collected packages: simplenote
    Running setup.py install for simplenote ... done
Successfully installed simplenote-2.1.4

~ took 2s 
➜ nvpy &                
[1] 6266

```

**Comment by yuuki0xff** [comment]
How did you install nvpy?

I found two AUR packages ([nvpy](https://aur.archlinux.org/packages/nvpy/) and [nvpy-git](https://aur.archlinux.org/packages/nvpy-git/)). Both packages are dependent on the python-simplenote package. Therefore, the simplenote python package should be installed automatically by pacman.

**Comment by stuzenz** [comment]
I only saw this response now - apologies. Whatever issue was happening back then got resolved. I still use nvpy and enjoy it. Thank you!
