### ISSUE TITLE
Diacritics in tags cause nvpy to crash with 'UnicodeEncodeError: [..] ordinal not in range'

### ISSUE THREAD

**Issue by Feltzer** [cpbotha/nvpy#97]
First of I'd all like to thank you very much for developing nvpy. Combined with the mobile simplenote app it has been my one-stop solution for note-taking.

With that said I recently discovered a critical issue with tag editing:
## Overview

Tags that contain diacritics (e.g. öäü) cause the application to lock up and subsequently crash on every startup with the following error message:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1413, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 1255, in handler_search_entry
    utils.KeyValueObject(value=self.search_entry_var.get()))
  File "/usr/local/lib/python2.7/dist-packages/nvpy/utils.py", line 189, in notify_observers
    o(self, evt_type, evt)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/nvpy.py", line 534, in observer_view_change_entry
    self.notes_list_model.set_list(nn)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/nvpy.py", line 170, in set_list
    self.notify_observers('set:list', None)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/utils.py", line 189, in notify_observers
    o(self, evt_type, evt)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 1401, in observer_notes_list
    self.set_notes(notes_list_model.list)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 1478, in set_notes
    self.notes_list.append(o.note, utils.KeyValueObject(tagfound=o.tagfound))
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 291, in append
    self.text.insert(tk.END, '{0:<{w}}'.format(','.join(tags)[:cellwidth-1], w=cellwidth), ("tags",))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 12: ordinal not in range(128)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1413, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 498, in callit
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 1171, in handler_housekeeper
    ot = self.notes_list.get_title(i)
  File "/usr/local/lib/python2.7/dist-packages/nvpy/view.py", line 408, in get_title
    return self.note_headers[idx][NotesList.TITLE_COL]
IndexError: list index out of range
```

In order to restore nvpy to its working state I had to remove the notes in question from `~/.nvpy` and delete the corresponding synchronized notes in the web application
## Steps to reproduce
1. Open nvpy
2. Create a new note with a random text passage
3. add a tag containing diacritics to the note, e.g. `nöte`
4. Close nvpy and try to launch it again from a terminal session. You should see the error message above

**Edit**: this bug also seems to appear with other special characters, e.g. `→` and `✔`:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 10: ordinal not in range(128) 
```

Notes that manage to get synced before the application locks up render fine in the web application.
## Additional information
- version installed: 0.9.4
- installed with `pip install`
- System: Ubuntu 12.04 LTS @ Linux 3.12.6

**Comment by yuuki0xff** [comment]
This issue can not reproduce with the latest version. It has probably been fixed. Please use the latest version.  If this problem still persists, reopen it again.
